import { ChainId } from '@wagyu-swap/sdk'
import addresses from './addresses.json'
import { serializeTokens } from './tokens'
import { SerializedPoolConfig, PoolCategory } from './types'

const chainId = parseInt(process.env.REACT_APP_CHAIN_ID, 10)
const { MAINNET } = ChainId

const serializedTokens = serializeTokens()

const pools: SerializedPoolConfig[] =
  chainId === MAINNET
    ? [
        {
          sousId: 0,
          stakingToken: serializedTokens.cake,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0x8a226293bC6f697A681B0b29f825c149655fEC2d',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 1,
          isFinished: false,
        },
        {
          sousId: 1,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.usdc,
          contractAddress: {
            137: '0x0560829c353efcda2f2f15be15753340b48d44a1',
            80001: '',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 2,
          isFinished: false,
        },
        {
          sousId: 2,
          stakingToken: serializedTokens.shib,
          earningToken: serializedTokens.lazermoon,
          contractAddress: {
            80001: '',
            137: '0x0a73a763b1a897db8cc7d77a7db96b10d727487a',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 3,
          isFinished: false,
        },
        {
          sousId: 3,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.kom,
          contractAddress: {
            80001: '',
            137: '0x176cf3b3161fab36fe6a8d18facda391745dcd34',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 4,
          isFinished: false,
        },
        {
          sousId: 4,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.grt,
          contractAddress: {
            80001: '',
            137: '0x357926e88da8434e16e3a3b951dbef5cddbd7a7f',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 5,
          isFinished: false,
        },
        {
          sousId: 5,
          stakingToken: serializedTokens.banana,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0x481db2ad06539c8b378647e866679248ddb1b350',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 6,
          isFinished: false,
        },
        {
          sousId: 6,
          stakingToken: serializedTokens.shib,
          earningToken: serializedTokens.zolamo,
          contractAddress: {
            80001: '',
            137: '0x5c0593b2fd62160ee0f1679bed172ea8c2748e7f',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 7,
          isFinished: false,
        },
        {
          sousId: 7,
          stakingToken: serializedTokens.kom,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0x64dcbe9ba04ffae0834133c2cf18163a159a34d0',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 8,
          isFinished: false,
        },
        {
          sousId: 8,
          stakingToken: serializedTokens.shib,
          earningToken: serializedTokens.elon,
          contractAddress: {
            80001: '',
            137: '0x6ca5d03933d7c02ba0fe4d76f4579b9be3f74dc9',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 9,
          isFinished: false,
        },
        {
          sousId: 9,
          stakingToken: serializedTokens.quick,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0x747af9b21ff5ec6cbf562f77d18bbb08e5da13ee',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 10,
          isFinished: false,
        },
        {
          sousId: 10,
          stakingToken: serializedTokens.usdc,
          earningToken: serializedTokens.banana,
          contractAddress: {
            80001: '',
            137: '0x7a74669059016a587d2fa5b3c377707a551a2b45',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 11,
          isFinished: false,
        },
        {
          sousId: 11,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.zolamo,
          contractAddress: {
            80001: '',
            137: '0x8a2df6d7d3695d6e620b1e56890e70bdb25f0d95',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 12,
          isFinished: false,
        },
        {
          sousId: 12,
          stakingToken: serializedTokens.mana,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0x8d55dcd84a9bd2afde95848faf7a00a9bbea0b9b',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 13,
          isFinished: false,
        },
        {
          sousId: 13,
          stakingToken: serializedTokens.cake,
          earningToken: serializedTokens.lazermoon,
          contractAddress: {
            80001: '',
            137: '0x9fd38c0ba9b6c69545db1e265f17a4464b00062d',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 14,
          isFinished: false,
        },
        {
          sousId: 14,
          stakingToken: serializedTokens.cake,
          earningToken: serializedTokens.shib,
          contractAddress: {
            80001: '',
            137: '0xa65bc835a3087f3f646914f14cfdeb55b6dfcd58',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 15,
          isFinished: false,
        },
        {
          sousId: 15,
          stakingToken: serializedTokens.cake,
          earningToken: serializedTokens.dai,
          contractAddress: {
            80001: '',
            137: '0xb4ee217f4b37ca079f654bcf3da1b6e76bfbe01e',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 16,
          isFinished: false,
        },
        {
          sousId: 16,
          stakingToken: serializedTokens.luna,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0xc44582cd763d8a38a8abdcdcb5c7aff77debcb22',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 17,
          isFinished: false,
        },
        {
          sousId: 18,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.mana,
          contractAddress: {
            80001: '',
            137: '0xc7283b4dac72bbb7754cf61359ea9d253ef7b73b',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 18,
          isFinished: false,
        },
        {
          sousId: 19,
          stakingToken: serializedTokens.wbtc,
          earningToken: serializedTokens.matic,
          contractAddress: {
            80001: '',
            137: '0xd324191782ba5e37afd262c08d67997fc6ffe70d',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 19,
          isFinished: false,
        },
        {
          sousId: 20,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.quick,
          contractAddress: {
            80001: '',
            137: '0xe2ee5a6738ce4ac42c94433d4cbae764b6fc7d09',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 20,
          isFinished: false,
        },
        {
          sousId: 21,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.elon,
          contractAddress: {
            80001: '',
            137: '0xf0ce4c5150c2bf1f36582f7375075e1ffae1245c',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 21,
          isFinished: false,
        },
        {
          sousId: 22,
          stakingToken: serializedTokens.usdt,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0xf72088149604e36a745f4d76fab03fd3ac39dcdc',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 22,
          isFinished: false,
        },
        {
          sousId: 23,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.lazermoon,
          contractAddress: {
            80001: '',
            137: '0xffb233ca5c6afcfedb9292080e6a45ed1c997a75',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 23,
          isFinished: false,
        },
        {
          sousId: 24,
          stakingToken: serializedTokens.matic,
          earningToken: serializedTokens.skilyne,
          contractAddress: {
            80001: '',
            137: '0x7ddC0E80eBA600DbF15B1e80a008d2Eb2053B024',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 24,
          isFinished: false,
       },
      ]
    : [
        {
          sousId: 0,
          stakingToken: serializedTokens.cake,
          earningToken: serializedTokens.cake,
          contractAddress: {
            80001: '',
            137: '0xDA5B294F6a8Af4236F853D17d33ba584D7787f10',
          },
          poolCategory: PoolCategory.CORE,
          harvest: true,
          tokenPerBlock: '1',
          sortOrder: 1,
          isFinished: false,
        },
      ]

export default pools
